### ISSUE TITLE
How to delete this conda feedstock project?

### ISSUE THREAD

**Issue by agrouaze** [conda-forge/xsarslc-feedstock#25]
### Comment:

@conda-forge/help-python 
Hi,
We would like to remove the `xsarslc-feedstock` project. We don't have the permission to do that. Could you help us?
thanks

**Comment by ocefpaf** [comment]
You can archive it, not delete. Also, bare in mind that the existing artifacts are still available for users. What is the reason for the request BTW?

**Comment by agrouaze** [comment]
We do not want to share the present/future code (publication in peer review journal foreseen). 
What do you call artifacts?

**Comment by ocefpaf** [comment]
> We do not want to share the present/future code (publication in peer review journal foreseen).

You can archive it and no new packages will be built.
See https://github.com/conda-forge/admin-requests?tab=readme-ov-file#archive-or-unarchive-a-feedstock

> What do you call artifacts?

The packages already built and distributed. Those are are GPL licensed and OSS at the moment if their creation. We only remove past artifacts if they are terribly broken to prevent a reproducibility problem for those doing good science.

**Comment by agrouaze** [comment]
Ok thanks for the explanation.
I will archive it then. 
A last question about https://anaconda.org/conda-forge/xsarslc/ ,  is there a way to know if the "10863 total downloads" are only bots?

**Comment by ocefpaf** [comment]
> A last question about https://anaconda.org/conda-forge/xsarslc/ , is there a way to know if the "10863 total downloads" are only bots?

Nope. And probably not most bots. Packages that are the "base" for science, like numpy, can be in tons of CIs and have thousands of bot downloads. Others, like this one, that are on the other side, more like the ones that users install and run to get specific results, are usually less bot heavy and the most of those downloads are probably real people.
